### ISSUE TITLE
chat window exceeds width on mobile devices . Set min-width to 360px instead of 400px

### ISSUE THREAD

**Issue by lubber-de** [Gurubase/gurubase-widget#35]
## Description
The min width by the chat window is set to 400px. This exceeds many mobile device default which is 360px (try chrome dev tools to emulate mobile device.

I suggest to set

```css
@media (max-width: 768px) {
    .chat-window {
        min-width: 360px;
    }
}
```

You may consider all other 400px settings to 360px as well, at least for the same media query until 768px width
