### ISSUE TITLE
larger tooltips on "top" are shown off canvas, add "top right" or similiar to adjust the tooltip to the top right

### ISSUE THREAD

**Issue by lubber-de** [Gurubase/gurubase-widget#36]
## Description

Our tooltip is a bit more text. Displaying it to the left moved the tooltip off canvas on mobile devices.
So we tried "data-tooltip-side="top" which would allow for enough space, but as the chat button is positioned bottom right the tooltip gets off canvas to the right again

Suggested fix/addon/workaound
 ```css
#gurubase-chat-widget-container .chat-button[data-tooltip-side="top"]::before {
    transform: none;
    margin-bottom: 8px;
    right: 0;
    left: auto;
}
```

### Before

![Image](https://github.com/user-attachments/assets/2b3dec74-8226-4916-a2f7-44def7e9fbd7)

### After

![Image](https://github.com/user-attachments/assets/0d8ce7bd-81e9-4293-80cd-1af4463f33ac)
